#!/bin/sh

GITHUB_TOKEN=$1
OWNER=$2
REPO=$3
ENV_NAME=$4
FILENAME='docker-compose'

if [[ ! -z "$ENV_NAME" ]]; then
  FILENAME="${FILENAME}${ENV_NAME}"
fi

CURL_PATH="https://api.github.com/repos/$OWNER/$REPO/contents/$FILENAME.yml"


get_compose_file () {

  curl --header "Authorization: token $GITHUB_TOKEN" \
     --header 'Accept: application/vnd.github.v3.raw' \
     --remote-name \
     --location $CURL_PATH

}

get_compose_file