#!/bin/sh

GITHUB_TOKEN="40fce352dbb62ce271be65f236724bab4cd2a33c"
OWNER="claramelo"
REPO="bemol-teste"
FILENAME="docker-compose.production"

CURL_PATH="https://api.github.com/repos/$OWNER/$REPO/contents/$FILENAME.yml"


get_compose_file () {

  curl --header "Authorization: token $GITHUB_TOKEN" \
     --header 'Accept: application/vnd.github.v3.raw' \
     --remote-name \
     --location $CURL_PATH

}

get_compose_file