#!/bin/sh

GITHUB_TOKEN=$1
OWNER=$2
REPO=$3
FILENAME="docker-compose.production"

CURL_PATH="https://api.github.com/repos/${OWNER}/${REPO}/contents/${FILENAME}.yml"

echo ${CURL_PATH} >> owner.txt
echo ${GITHUB_TOKEN} >> a.txt

get_compose_file () {

  curl --header "Authorization: token ${GITHUB_TOKEN}" \
     --header 'Accept: application/vnd.github.v3.raw' \
     --remote-name \
     --location $CURL_PATH

}

get_compose_file