#!/bin/bash
mode=$1

get_deploy_swarm_ip () {
  terraform init > log.init
  rm log.init
  swarm_ip=$(terraform output -json deploy_swarm_ip | tr -d '\"')

  echo $swarm_ip
}

get_host_file () {
  terraform init > log.init
  rm log.init
  leader_ip=$(terraform output -json cluster_swarm_leader_ip | tr -d '\"')
  workers_ip=$(terraform output -json cluster_swarm_workers_ip | tr -d '\[\"\*\]')
  hosts_ips="[masters]\n$leader_ip\n\n[workers]\n${workers_ip//','/'\n'}"
  
  echo $hosts_ips
} 

if [[ $mode == 'provision-infra' ]]; then
  terraform init
  terraform plan
  terraform apply -auto-approve
fi

if [[ $mode == 'deploy-swarm-ip' ]]; then
  get_deploy_swarm_ip
fi

if [[ $mode == 'get-hosts-file' ]]; then
  get_host_file
fi

if [[ $mode == 'destroy-infra' ]]; then
  terraform init
  terraform plan
  terraform destroy -auto-approve
fi
