version: 2.1

jobs:
  terraform-validate:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Valida os arquivos terraform
          command: |
            cd terraform
            terraform init -backend=false
            terraform validate
  
  build-push-terraform:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker Login
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Build da imagem do terraform
          command: |
            cd terraform
            docker build . --file Dockerfile \
                        --build-arg "aws_access_key_id=${AWS_ACCESS_KEY_ID}" \
                        --build-arg "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" \
                        --tag  "${DOCKER_USER}/provision-infra:latest"
      - run:
          name: Push imagem
          command: |
            docker push "${DOCKER_USER}/provision-infra:latest"
  
  build-push-ansible:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker Login
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Build da imagem do Ansible
          command: |
            cd ansible
            docker build . --file Dockerfile \
                           --tag  "${DOCKER_USER}/swarm-cluster-provider:latest"
      - run:
          name: Push imagem do Ansible
          command: |
            docker push "${DOCKER_USER}/swarm-cluster-provider:latest"

workflows:
  version: 2
  bemol-terraform-workflow:
    jobs:
      - terraform-validate
      - build-push-terraform:
          context: common-credentials
          requires:
            - terraform-validate
          filters:
            branches:
              only:
                - master
      - build-push-ansible:
          context: common-credentials
          filters:
            branches:
              only:
                - master

