#!/bin/bash
MODE=$1
HOSTS_IPS=$2

echo -e ${HOSTS_IPS//'n'/'\n'} > hosts

if [[ $MODE == 'create-cluster' ]]; then
  ansible-playbook -i /ansible/hosts /ansible/create-swarm-cluster.yml
fi

if [[ $MODE == 'deploy' ]]; then
  GITHUB_TOKEN=$3
  OWNER=$4
  REPO_NAME=$5
  
  ansible-playbook -i /ansible/hosts /ansible/deploy-stack.yml --extra-vars "{"github_token": ${GITHUB_TOKEN}, "repo_owner": ${OWNER}, "repo_name": ${REPO_NAME}}"
fi