#!/bin/bash
mode=$1
hosts_ips=$2

pwd
echo -e $hosts_ips > inventory/hosts

if [[ $mode == 'create-cluster' ]]; then
  ansible-playbook -i /ansible/inventory/hosts /ansible/create-swarm-cluster.yml
fi

if [[ $mode == 'deploy' ]]; then
  GITHUB_TOKEN=$3
  OWNER=$4
  REPO=$5
  ENV_NAME=$6

  ansible-playbook -i /ansible/inventory/hosts /ansible/deploy-stack.yml --extra-var "github_token=$GITHUB_TOKEN repo_owner=$OWNER repo_name=$REPO env_name=$ENV_NAME"
fi